---
title: "MLR with Correlated Errors with Seasonality and ARIMA"
author: "Nikhil Gupta"
date: "`r Sys.time()`"
output:
  word_document:
    toc: yes
    toc_depth: '6'
  html_document:
    toc: yes
    toc_depth: 6
    toc_float: yes
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tswge)
library(dplyr)
```

# Load Data
```{r}
#ARIMA 2: attempt at categorical variable for week but arima takes only continuous variables (can be fixed with model matrix)

CM = read.csv(file.choose(),header = TRUE)
head(CM)
```

# Forecast Independent Variables

## Particles
```{r}
#forecast Particles
px = plotts.sample.wge(CM$part) #freq near .0192 (annual)
CM_52 = artrans.wge(CM$part, c(rep(0,51),1))
px = plotts.sample.wge(CM_52) #looks like some low freq?
aic5.wge(CM_52) #picks ARMA(2,1) assume stationary
aic5.wge(CM_52,type = "bic") #picks ARMA(0,0) 
ljung.wge(CM_52)$pval #FTR Ho
ljung.wge(CM_52, K = 48)$pval #FTR Ho
#Going with white noise despite peak at 0 in Spec D. 
#est = est.arma.wge(CM_52, p = 3, q = 2)
#CM_52_AR2_MA1 = artrans.wge(CM_52,est$phi)
predsPart = fore.aruma.wge(CM$part,s = 52, n.ahead = 20)
```

## Temp
```{r}
#forecast Temp
px = plotts.sample.wge(CM$temp) #freq near .0192 (annual)
CM_52 = artrans.wge(CM$temp, c(rep(0,51),1))
px = plotts.sample.wge(CM_52) #looks like some low freq?
aic5.wge(CM_52) #picks ARMA(0,0)
aic5.wge(CM_52,type = "bic") #picks ARMA(0,0) 
ljung.wge(CM_52)$pval
ljung.wge(CM_52, K = 48)$pval #barely rejects
acf(CM_52,lag.max = 48) # acf looks consistent with white noise
predsTemp = fore.aruma.wge(CM$temp,s = 52, n.ahead = 20)
```

# Feature Engineering
```{r}
CM$FWeek = as.factor(CM$Week%%52)

form = ~ .  # Since we are using all variables in the dataframe
form = ~ cmort+temp+part+Week+FWeek  # or explicitly add variables to use

CMexpanded = model.matrix(form, data = CM) %>%  
  as_tibble() %>% 
  dplyr::select(-"(Intercept)")

# colnames(CMexpanded)
```

# Fit MLR and evalulate residuals
```{r}
ksfit = lm(cmort~., data = CMexpanded)
summary(ksfit)

## Evaluate Residuals
px = tswge::plotts.sample.wge(ksfit$residuals)
## Looks stationary AR(1) ,ay be appropriate

aic_resids = aic.wge(ksfit$residuals)  # Picks AR(2)
print(aic_resids)
```

# Fit ARIMA with parameters found in previous step

```{r}
fit = arima(CMexpanded$cmort,order = c(aic_resids$p,0,aic_resids$q), xreg = CMexpanded %>% dplyr::select(-cmort))
print(fit)
AIC(fit) #AIC = 3088.997

# Check for whiteness of residuals
acf(fit$residuals)
ljung.wge(fit$residuals) # pval = .0808
ljung.wge(fit$residuals, K = 48) # pval = 0.123916
```

# Predictions

## Data Prep
```{r}
#load the forecasted Part and Temp in a data frame
next20 = data.frame(temp = predsTemp$f, part = predsPart$f, Week = seq(509,528,1), FWeek = factor(seq(509,528,1)%%52, levels = levels(CM$FWeek)))
form = ~ temp + part + Week + FWeek  # Remove the dependent variable 'cmort'
next20expanded = model.matrix(form, data = next20) %>%   
  as_tibble() %>% 
  dplyr::select(-"(Intercept)")
# colnames(next20expanded)
```

## Make and Plot Predictions
```{r}
#get predictions
predsCMort = predict(fit,newxreg = next20expanded) #creates error because of factor

#plot next 20 cmort wrt time
plot(seq(1,508,1), CM$cmort, type = "l",xlim = c(0,528), ylab = "Cardiac Mortality", main = "20 Week Cardiac Mortality Forecast")
lines(seq(509,528,1), predsCMort$pred, type = "l", col = "red")
```



