---
title: "Live Session Assignment 13"
author: "Nikhil Gupta"
date: "`r Sys.time()`"
output:
  github_document:
    toc: yes
    toc_depth: 6
  word_document:
    toc: yes
    toc_depth: '6'
  html_document:
    toc: yes
    toc_depth: 6
    toc_float: yes
always_allow_html: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r}
library(tswge)
library(tswgewrapped)
library(tidyverse)
library(tseries)
library(orcutt)
library(vars)
library(RColorBrewer)
library(nnfor)
```

# Sunspot Melanoma Data

```{r}
# # melanoma incidence and sunspot numbers 1936-1972
# melanoma=c(1.0, 0.9, 0.8, 1.4, 1.2, 1.0, 1.5, 1.9, 1.5, 1.5, 1.5, 1.6, 1.8, 2.8, 2.5, 2.5, 2.4, 2.1, 1.9, 2.4, 2.4, 2.6, 2.6, 4.4, 4.2, 3.8, 3.4, 3.6, 4.1, 3.7, 4.2, 4.1, 4.1, 4.0, 5.2, 5.3, 5.3)
# sunspot=c(40, 115, 100,  80,  60,  40,  23,  10,  10,  25,  75, 145, 130, 130,  80,  65,  20,  10,   5,  10, 60, 190, 180, 175, 120,  50,  35,  20,  10,  15,  30,  60, 105, 105, 105,  80,  65)

data = read.csv("../MSDS-6373-Time-Series/Unit 13/Melanoma_Sunspot.csv", header = TRUE)
data %>% glimpse()
```

```{r}
data_train = data %>% slice(1:29)
data_test = data %>% slice(30:37)
```

## Modeling

### Manual

```{r}
set.seed(2)

## Regressor lags will be picked automatically
fit = nnfor::mlp(y = ts(data_train$Melanoma, start = c(1936), frequency = 1),
                 xreg = data.frame(Sunspot = ts(data_train$Sunspot,  start = c(1936), frequency = 1))
                 )
fit
```

```{r}
h = 8

# Must include entire dataset to xreg for predict

f = forecast(fit,  h = h, xreg = data.frame(Sunspot = ts(data$Sunspot, start = c(1936), frequency = 1)))
plot(data$Melanoma,type = "l", ylab = "Time Series")
lines(seq(nrow(data_train)+1,nrow(data)), f$mean, col = "blue")
ASE = mean((data$Melanoma %>% tail(h) - f$mean)^2)
ASE
```

### tswgewrapped

```{r}
# Fit Model
set.seed(2)

var_interest = 'Melanoma'
batch_size = 29
n.ahead = 8

# Random Parallel
model = ModelBuildNNforCaret$new(data = data_train %>% dplyr::select(-Year),
                                 var_interest = var_interest,
                                 m = 1,
                                 search = 'random',
                                 grid = NA, tuneLength = 10,
                                 batch_size = batch_size, h = n.ahead,
                                 parallel = TRUE,
                                 seed = 1,
                                 verbose = 1
                                )

```

```{r}
model$summarize_hyperparam_results()
```

```{r}
model$summarize_best_hyperparams()
```

```{r}
## Print model (recommended - best hyperparameters)
model$get_final_models(subset = 'r')
```

```{r}
caret_model = model$get_final_models(subset = 'a')

# Initialize the ModelCompareNNforCaret object
mdl_compare_mlp = ModelCompareNNforCaret$new(data = data_train,
                                             var_interest = var_interest,
                                             mdl_list = caret_model,
                                             verbose = 0)
```

```{r}
p = mdl_compare_mlp$plot_batch_ases(only_sliding = FALSE)
p$ASEs
```

```{r}
newxreg = data_test %>% dplyr::select(-!!var_interest, -Year)
```

```{r}
batchf = mdl_compare_mlp$plot_batch_forecasts(only_sliding = FALSE)
batchf$forecasts
```


```{r}
f = mdl_compare_mlp$plot_simple_forecasts(newxreg = newxreg)
f$forecasts
```

```{r}
plot(data$Melanoma,type = "l")
lines(seq(30, 37),f$forecasts$f, col = "blue")
```

```{r}
ASE = mean((data_test$Melanoma-f$forecasts$f)^2)
ASE
```

# Schumway pollution data

```{r}
data = read.csv("../Datasets/la_cmort_study.csv", header = TRUE)
data %>% glimpse()
```

```{r}
data_train = data %>% slice(1:498)
data_test = data %>% slice(499:508)
```

## Modeling

### Manual
```{r}
set.seed(2)

## Note that xreg has to be a dataframe else it will not work

fit = nnfor::mlp(y = ts(data_train$cmort, frequency = 52),
                 xreg = data.frame(temp = ts(data_train$temp, frequency = 52),
                                   part = ts(data_train$part, frequency = 52)),
                 xreg.lags = (list(1:13, 1:13)), allow.det.season = FALSE,
                 hd = 1
                 )
                 
fit
```

```{r}
plot(fit)
```

```{r}
h = 10

f = forecast(fit,  h = h, xreg = data.frame(temp = ts(data$temp, frequency = 52),
                                            part = ts(data$part, frequency = 52)))

plot(f)
plot(data$cmort, type = "l", ylab = "Time Series")
lines(seq(nrow(data_train)+1,nrow(data)), f$mean, col = "blue")
ASE = mean((data$cmort %>% tail(h) - f$mean)^2)
ASE
```

### tswgewrapped

```{r}
# Exploratory Analysis
eda = MultivariateEDA$new(data = data,
                          var_interest = 'cmort',
                          var_time = 'Week')


eda$plot_ccf_analysis(negative_only = TRUE)
```

```{r}
# Fit Model
set.seed(1)

var_interest = 'cmort'
batch_size = 470
n.ahead = 10

# grid_size = 10
# reps = sample(1:25, grid_size, replace = TRUE)
# hd = sample(1:10, grid_size, replace = TRUE, prob = c(10:1))
# allow.season.detect = rep(FALSE, grid_size)

grid_size = 1
reps = 20
hd = 1
allow.det.season = FALSE

nngrid = data.frame(reps = reps,
                    hd = hd,
                    allow.det.season = allow.det.season
                    )

# Random Parallel
model = ModelBuildNNforCaret$new(data = data_train %>% dplyr::select(-Week),
                                 var_interest = var_interest,
                                 m = 52,
                                 search = 'grid',
                                 grid = nngrid, tuneLength = NA,
                                 batch_size = batch_size, h = n.ahead,
                                 parallel = TRUE,
                                 seed = 1,
                                 verbose = 1,
                                 difforder = c(1),
                                 sel.lag = TRUE,  ## If FALSE, then it keeps all lags, If TRUE, it may remove some, applied to both univariate and xreg
                                 lags = 1:52, ## Which univariate lags to try
                                 keep = rep(TRUE, 52), ## Which univariate lags to be forced to be kept
                                 xreg.lags = (list(1:13, 1:13)) ## Which xreg lags to try
                                )

```

```{r}
model$summarize_hyperparam_results()
```

```{r}
model$summarize_best_hyperparams()
```

```{r}
## Print model (recommended - best hyperparameters)
model$get_final_models(subset = 'r')
```

```{r}
caret_model = model$get_final_models(subset = 'a')

# Initialize the ModelCompareNNforCaret object
mdl_compare_mlp = ModelCompareNNforCaret$new(data = data_train,
                                             var_interest = var_interest,
                                             mdl_list = caret_model,
                                             verbose = 0)
```

```{r}
p = mdl_compare_mlp$plot_batch_ases(only_sliding = FALSE)
p$ASEs %>% na.omit()
```

```{r}
newxreg = data_test %>% dplyr::select(-!!var_interest, -Week)
```

```{r}
batchf = mdl_compare_mlp$plot_batch_forecasts(only_sliding = FALSE)
batchf$forecasts
```


```{r}
f = mdl_compare_mlp$plot_simple_forecasts(newxreg = newxreg)
f$forecasts
```

```{r}
plot(data$cmort,type = "l")
lines(seq(499, 508),f$forecasts$f, col = "blue")
```

```{r}
ASE = mean((data_test$cmort-f$forecasts$f)^2)
ASE
```

# My data

```{r}
electrictiy = read.csv("../Datasets/electricity_usage_nikhil_house.csv")
head(electrictiy)
```

* There are some missing values. We will need to impute these

```{r}
data = ts(electrictiy$Usage, frequency = 12, start = c(2009, 12))

library(imputeTS)
data = imputeTS::na_interpolation(data, option = 'spline')
data = data.frame(data)
```

```{r}
plot(data)
```

```{r}
data_train = data %>% slice(1:102)
data_test = data %>% slice(103:114)
```

## Modeling

```{r}
set.seed(2)

## Note that xreg has to be a dataframe else it will not work
fit = nnfor::mlp(y = ts(data_train$data, frequency = 12), lags = 1:12, difforder = c(12), hd = 1) 
fit
```

```{r}
plot(fit)
```
```{r}
h = 12

f = forecast(fit,  h = h)

plot(f)
plot(as.numeric(data$data), type = "l", ylab = "Time Series")
lines(seq(nrow(data_train)+1,nrow(data)), f$mean, col = "blue")
ASE = mean((as.numeric(data$data) %>% tail(h) - f$mean)^2)
ASE
```

## Univariate Modeling
```{r}
data_train = data_train$data
px = plotts.sample.wge(data_train)
```
```{r}
# Remove seasonality
xdif12 = artrans.wge(data_train, phi.tr = c(rep(0,11),1))
px = plotts.sample.wge(xdif12)
```

```{r}
aic5.wge(xdif12, p = 0:12)
```

```{r}
e = est.arma.wge(xdif12, p = 12, q = 0)
e$theta

evaluate_residuals(e$res, p = 12)
```

```{r}
f = fore.aruma.wge(data_train, phi = e$phi, theta = e$theta, s = 12, n.ahead = 12)
```

```{r}
plot(as.numeric(data$data), type = "l", ylab = "Time Series")
lines(seq(length(data_train)+1,nrow(data)), f$f, col = "blue")

ASE = mean((f$f - data_test$data)^2)
ASE
```

