---
title: "Time Series - Async Week 1"
author: "Nikhil Gupta"
date: "`r Sys.time()`"
output:
  word_document:
    toc: yes
    toc_depth: '6'
  html_document:
    toc: yes
    toc_depth: 6
    toc_float: yes
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tswge)
source("common_functions.R")
```

# Noctula vs Lavon (Stationarity)

```{r}
data("noctula")
plot(noctula)
acf(noctula[1:48])
acf(noctula[49:96])
```

```{r}
data("lavon") 
plot(lavon)
acf(lavon[1:56])
acf(lavon[57:112])
```


# Whale Dataset (Staionarity)

```{r}
data("whale")
plot(whale)
lines(whale)
len = length(whale)
len_by_2 = round(len/2)
seg_2_start = len_by_2+1
acf(whale[1:len_by_2])
acf(whale[seg_2_start:len])
```

```{r}
# Checking functionality of function
check_stationarity(whale)
```


```{r}
bond = read.csv("../Datasets/10_year_bond_rate_2010-2015.csv")
head(bond)

check_stationarity(bond$Adj.Close)

```


# Estimating the Variance of (the mean) a Stationary Series

# Common Functions
```{r}
calculate_ts_gamma0 = function(x){
  n = length(x)
  gamma0 = var(x)*(n-1)/n
  return(gamma0)
}

calculate_ts_mean = function(x){
  return(mean(x))
}

calculate_ts_var_of_mean = function(x){
  n=length(x) 
  nlag=n-1 
  m=mean(x)
  v=var(x,na.rm = TRUE)
  gamma0=calculate_ts_gamma0(x)
  aut=acf(x,lag.max=nlag) 
  sum=0
  for (k in 1:nlag) {
    sum=sum+(1-k/n)*aut$acf[k+1]*gamma0
  }
  
  vxbar=2*sum/n + gamma0/n 
  return(vxbar)  
}

calculate_ts_mean_confidence_interval = function(x, alpha = 0.05){
  xbar = calculate_ts_mean(x)
  vxbar = calculate_ts_var_of_mean(x)
  multiplier = qnorm(1 - alpha/2)
  ci = c(xbar - multiplier * sqrt(vxbar), xbar +  multiplier * sqrt(vxbar))
  return(ci)
}


```


```{r}
#xdf = read.csv(file.choose(),header = TRUE)
xdf = read.csv("../Datasets/10_year_bond_rate_2010-2015.csv",header = TRUE)
x = as.numeric(paste(xdf$Adj.Close))
x = x[!is.na(x)]
plotts.wge(x = x)

xbar = calculate_ts_mean(x)
print(xbar)
vxbar = calculate_ts_var_of_mean(x)
print(vxbar)
ci = calculate_ts_mean_confidence_interval(x)
print(ci)

```



```{r}
x = c(4,6,7,5,3)

gamma0 = calculate_ts_gamma0(x)
print(gamma0)
xbar = calculate_ts_mean(x)
print(xbar)
vxbar = calculate_ts_var_of_mean(x)
print(vxbar)
ci = calculate_ts_mean_confidence_interval(x)
print(ci)

```

